// All countries with flags, dial codes, and prefixes
export const COUNTRY_CODES = [
  { name: 'United States', code: 'US', flag: '🇺🇸', dialCode: '+1', prefix: '1' },
  { name: 'India', code: 'IN', flag: '🇮🇳', dialCode: '+91', prefix: '91' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', dialCode: '+44', prefix: '44' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', dialCode: '+1', prefix: '1' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', dialCode: '+61', prefix: '61' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', dialCode: '+49', prefix: '49' },
  { name: 'France', code: 'FR', flag: '🇫🇷', dialCode: '+33', prefix: '33' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', dialCode: '+81', prefix: '81' },
  { name: 'China', code: 'CN', flag: '🇨🇳', dialCode: '+86', prefix: '86' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', dialCode: '+65', prefix: '65' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', dialCode: '+971', prefix: '971' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', dialCode: '+52', prefix: '52' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', dialCode: '+55', prefix: '55' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', dialCode: '+27', prefix: '27' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', dialCode: '+31', prefix: '31' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', dialCode: '+34', prefix: '34' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', dialCode: '+39', prefix: '39' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', dialCode: '+46', prefix: '46' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', dialCode: '+41', prefix: '41' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', dialCode: '+64', prefix: '64' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', dialCode: '+82', prefix: '82' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', dialCode: '+66', prefix: '66' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', dialCode: '+84', prefix: '84' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', dialCode: '+63', prefix: '63' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', dialCode: '+62', prefix: '62' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', dialCode: '+60', prefix: '60' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', dialCode: '+92', prefix: '92' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', dialCode: '+880', prefix: '880' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dialCode: '+94', prefix: '94' },
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', dialCode: '+93', prefix: '93' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', dialCode: '+355', prefix: '355' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', dialCode: '+213', prefix: '213' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', dialCode: '+376', prefix: '376' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', dialCode: '+244', prefix: '244' },
  { name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬', dialCode: '+1-268', prefix: '1268' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', dialCode: '+54', prefix: '54' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', dialCode: '+374', prefix: '374' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', dialCode: '+43', prefix: '43' },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', dialCode: '+994', prefix: '994' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', dialCode: '+1-242', prefix: '1242' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', dialCode: '+973', prefix: '973' },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', dialCode: '+375', prefix: '375' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', dialCode: '+32', prefix: '32' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', dialCode: '+501', prefix: '501' },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', dialCode: '+229', prefix: '229' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', dialCode: '+975', prefix: '975' },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴', dialCode: '+591', prefix: '591' },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', dialCode: '+387', prefix: '387' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', dialCode: '+267', prefix: '267' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', dialCode: '+359', prefix: '359' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', dialCode: '+226', prefix: '226' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', dialCode: '+257', prefix: '257' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', dialCode: '+855', prefix: '855' },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', dialCode: '+237', prefix: '237' },
  { name: 'Cape Verde', code: 'CV', flag: '🇨🇻', dialCode: '+238', prefix: '238' },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫', dialCode: '+236', prefix: '236' },
  { name: 'Chad', code: 'TD', flag: '🇹🇩', dialCode: '+235', prefix: '235' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', dialCode: '+56', prefix: '56' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', dialCode: '+57', prefix: '57' },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲', dialCode: '+269', prefix: '269' },
  { name: 'Congo', code: 'CG', flag: '🇨🇬', dialCode: '+242', prefix: '242' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', dialCode: '+506', prefix: '506' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', dialCode: '+385', prefix: '385' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', dialCode: '+53', prefix: '53' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', dialCode: '+357', prefix: '357' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', dialCode: '+420', prefix: '420' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', dialCode: '+45', prefix: '45' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', dialCode: '+253', prefix: '253' },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲', dialCode: '+1-767', prefix: '1767' },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', dialCode: '+1-809', prefix: '1809' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', dialCode: '+593', prefix: '593' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', dialCode: '+20', prefix: '20' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', dialCode: '+503', prefix: '503' },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', dialCode: '+240', prefix: '240' },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷', dialCode: '+291', prefix: '291' },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪', dialCode: '+372', prefix: '372' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', dialCode: '+251', prefix: '251' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', dialCode: '+679', prefix: '679' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', dialCode: '+358', prefix: '358' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', dialCode: '+241', prefix: '241' },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲', dialCode: '+220', prefix: '220' },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', dialCode: '+995', prefix: '995' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', dialCode: '+233', prefix: '233' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', dialCode: '+30', prefix: '30' },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩', dialCode: '+1-473', prefix: '1473' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', dialCode: '+502', prefix: '502' },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳', dialCode: '+224', prefix: '224' },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', dialCode: '+245', prefix: '245' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', dialCode: '+592', prefix: '592' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', dialCode: '+509', prefix: '509' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', dialCode: '+504', prefix: '504' },
  { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', dialCode: '+852', prefix: '852' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', dialCode: '+36', prefix: '36' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', dialCode: '+354', prefix: '354' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', dialCode: '+98', prefix: '98' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', dialCode: '+964', prefix: '964' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', dialCode: '+353', prefix: '353' },
  { name: 'Isle of Man', code: 'IM', flag: '🇮🇲', dialCode: '+44', prefix: '44' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', dialCode: '+972', prefix: '972' },
  { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', dialCode: '+225', prefix: '225' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', dialCode: '+1-876', prefix: '1876' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', dialCode: '+962', prefix: '962' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', dialCode: '+7', prefix: '7' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', dialCode: '+254', prefix: '254' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', dialCode: '+686', prefix: '686' },
  { name: 'Kosovo', code: 'XK', flag: '🇽🇰', dialCode: '+383', prefix: '383' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', dialCode: '+965', prefix: '965' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', dialCode: '+996', prefix: '996' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', dialCode: '+856', prefix: '856' },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', dialCode: '+371', prefix: '371' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', dialCode: '+961', prefix: '961' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', dialCode: '+266', prefix: '266' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', dialCode: '+231', prefix: '231' },
  { name: 'Libya', code: 'LY', flag: '🇱🇾', dialCode: '+218', prefix: '218' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', dialCode: '+423', prefix: '423' },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', dialCode: '+370', prefix: '370' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', dialCode: '+352', prefix: '352' },
  { name: 'Macao', code: 'MO', flag: '🇲🇴', dialCode: '+853', prefix: '853' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', dialCode: '+261', prefix: '261' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', dialCode: '+265', prefix: '265' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', dialCode: '+960', prefix: '960' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', dialCode: '+223', prefix: '223' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', dialCode: '+356', prefix: '356' },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭', dialCode: '+692', prefix: '692' },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷', dialCode: '+222', prefix: '222' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', dialCode: '+230', prefix: '230' },
  { name: 'Mayotte', code: 'YT', flag: '🇾🇹', dialCode: '+262', prefix: '262' },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩', dialCode: '+373', prefix: '373' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', dialCode: '+377', prefix: '377' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', dialCode: '+976', prefix: '976' },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', dialCode: '+382', prefix: '382' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', dialCode: '+212', prefix: '212' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', dialCode: '+258', prefix: '258' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', dialCode: '+95', prefix: '95' },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦', dialCode: '+264', prefix: '264' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', dialCode: '+674', prefix: '674' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', dialCode: '+977', prefix: '977' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', dialCode: '+505', prefix: '505' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪', dialCode: '+227', prefix: '227' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', dialCode: '+234', prefix: '234' },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵', dialCode: '+850', prefix: '850' },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰', dialCode: '+389', prefix: '389' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', dialCode: '+47', prefix: '47' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', dialCode: '+968', prefix: '968' },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', dialCode: '+970', prefix: '970' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', dialCode: '+507', prefix: '507' },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', dialCode: '+675', prefix: '675' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', dialCode: '+595', prefix: '595' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', dialCode: '+51', prefix: '51' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', dialCode: '+48', prefix: '48' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', dialCode: '+351', prefix: '351' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', dialCode: '+974', prefix: '974' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', dialCode: '+40', prefix: '40' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', dialCode: '+7', prefix: '7' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', dialCode: '+250', prefix: '250' },
  { name: 'Saint Helena', code: 'SH', flag: '🇸🇭', dialCode: '+290', prefix: '290' },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', dialCode: '+1-869', prefix: '1869' },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨', dialCode: '+1-758', prefix: '1758' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨', dialCode: '+1-784', prefix: '1784' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', dialCode: '+685', prefix: '685' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲', dialCode: '+378', prefix: '378' },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', dialCode: '+239', prefix: '239' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', dialCode: '+966', prefix: '966' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', dialCode: '+221', prefix: '221' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', dialCode: '+381', prefix: '381' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', dialCode: '+248', prefix: '248' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', dialCode: '+232', prefix: '232' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', dialCode: '+421', prefix: '421' },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', dialCode: '+386', prefix: '386' },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧', dialCode: '+677', prefix: '677' },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴', dialCode: '+252', prefix: '252' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩', dialCode: '+249', prefix: '249' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', dialCode: '+597', prefix: '597' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', flag: '🇸🇯', dialCode: '+47', prefix: '47' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', dialCode: '+963', prefix: '963' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', dialCode: '+886', prefix: '886' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', dialCode: '+992', prefix: '992' },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', dialCode: '+255', prefix: '255' },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱', dialCode: '+670', prefix: '670' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', dialCode: '+228', prefix: '228' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', dialCode: '+676', prefix: '676' },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', dialCode: '+1-868', prefix: '1868' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', dialCode: '+216', prefix: '216' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', dialCode: '+90', prefix: '90' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', dialCode: '+993', prefix: '993' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', dialCode: '+688', prefix: '688' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', dialCode: '+256', prefix: '256' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', dialCode: '+380', prefix: '380' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', dialCode: '+598', prefix: '598' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', dialCode: '+998', prefix: '998' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', dialCode: '+678', prefix: '678' },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦', dialCode: '+39', prefix: '39' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', dialCode: '+58', prefix: '58' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', dialCode: '+967', prefix: '967' },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲', dialCode: '+260', prefix: '260' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', dialCode: '+263', prefix: '263' },
]

export function getCountryByName(countryName: any) {
  if (!countryName) return COUNTRY_CODES[0]
  return COUNTRY_CODES.find(c => c.name.toLowerCase() === countryName.toLowerCase()) || COUNTRY_CODES[0]
}

export function getCountryByCode(code: any) {
  return COUNTRY_CODES.find(c => c.code === code)
}

export function searchCountries(query: any) {
  if (!query || query.trim() === '') {
    return COUNTRY_CODES
  }

  const lowerQuery = query.toLowerCase()

  // Exact matches first
  const exactMatches = COUNTRY_CODES.filter(c =>
    c.name.toLowerCase() === lowerQuery ||
    c.code.toLowerCase() === lowerQuery
  )

  // Starts with query
  const startsWithMatches = COUNTRY_CODES.filter(c =>
    !exactMatches.includes(c) && c.name.toLowerCase().startsWith(lowerQuery)
  )

  // Includes query
  const includesMatches = COUNTRY_CODES.filter(c =>
    !exactMatches.includes(c) &&
    !startsWithMatches.includes(c) &&
    c.name.toLowerCase().includes(lowerQuery)
  )

  return [...exactMatches, ...startsWithMatches, ...includesMatches]
}
