// Curated list of major global seaports and logistics hubs for RFQ targeting
const PORTS = [
  { name: 'Port of Singapore', country: 'Singapore' },
  { name: 'Jebel Ali Port', country: 'United Arab Emirates' },
  { name: 'Port of Shanghai', country: 'China' },
  { name: 'Port of Ningbo-Zhoushan', country: 'China' },
  { name: 'Port of Shenzhen', country: 'China' },
  { name: 'Port of Guangzhou', country: 'China' },
  { name: 'Port of Busan', country: 'South Korea' },
  { name: 'Port of Hong Kong', country: 'Hong Kong' },
  { name: 'Port of Kaohsiung', country: 'Taiwan' },
  { name: 'Port of Tokyo', country: 'Japan' },
  { name: 'Port of Yokohama', country: 'Japan' },
  { name: 'Port of Osaka', country: 'Japan' },
  { name: 'Port of Colombo', country: 'Sri Lanka' },
  { name: 'Port of Hambantota', country: 'Sri Lanka' },
  { name: 'Port of Mumbai', country: 'India' },
  { name: 'Port of Chennai', country: 'India' },
  { name: 'Port of Nhava Sheva', country: 'India' },
  { name: 'Port of Kolkata', country: 'India' },
  { name: 'Port of Mundra', country: 'India' },
  { name: 'Port of Kandla', country: 'India' },
  { name: 'Port of Visakhapatnam', country: 'India' },
  { name: 'Port of Cochin', country: 'India' },
  { name: 'Port of Karachi', country: 'Pakistan' },
  { name: 'Port of Doha', country: 'Qatar' },
  { name: 'Port of Salalah', country: 'Oman' },
  { name: 'Port of Djibouti', country: 'Djibouti' },
  { name: 'Port of Alexandria', country: 'Egypt' },
  { name: 'Port Said', country: 'Egypt' },
  { name: 'Port of Port Sudan', country: 'Sudan' },
  { name: 'Port of Mombasa', country: 'Kenya' },
  { name: 'Port of Dar es Salaam', country: 'Tanzania' },
  { name: 'Port of Durban', country: 'South Africa' },
  { name: 'Port of Cape Town', country: 'South Africa' },
  { name: 'Port of Ngqura', country: 'South Africa' },
  { name: 'Port of Rotterdam', country: 'Netherlands' },
  { name: 'Port of Antwerp', country: 'Belgium' },
  { name: 'Port of Hamburg', country: 'Germany' },
  { name: 'Port of Bremerhaven', country: 'Germany' },
  { name: 'Port of Le Havre', country: 'France' },
  { name: 'Port of Marseille', country: 'France' },
  { name: 'Port of Valencia', country: 'Spain' },
  { name: 'Port of Barcelona', country: 'Spain' },
  { name: 'Port of Algeciras', country: 'Spain' },
  { name: 'Port of Genoa', country: 'Italy' },
  { name: 'Port of La Spezia', country: 'Italy' },
  { name: 'Port of Piraeus', country: 'Greece' },
  { name: 'Port of Istanbul', country: 'Turkey' },
  { name: 'Port of Izmir', country: 'Turkey' },
  { name: 'Port of Constanța', country: 'Romania' },
  { name: 'Port of Odessa', country: 'Ukraine' },
  { name: 'Port of Novorossiysk', country: 'Russia' },
  { name: 'Port of St. Petersburg', country: 'Russia' },
  { name: 'Port of London', country: 'United Kingdom' },
  { name: 'Port of Felixstowe', country: 'United Kingdom' },
  { name: 'Port of Liverpool', country: 'United Kingdom' },
  { name: 'Port of New York', country: 'United States' },
  { name: 'Port of Newark', country: 'United States' },
  { name: 'Port of Los Angeles', country: 'United States' },
  { name: 'Port of Long Beach', country: 'United States' },
  { name: 'Port of Savannah', country: 'United States' },
  { name: 'Port of Houston', country: 'United States' },
  { name: 'Port of Miami', country: 'United States' },
  { name: 'Port of Montreal', country: 'Canada' },
  { name: 'Port of Vancouver', country: 'Canada' },
  { name: 'Port of Halifax', country: 'Canada' },
  { name: 'Port of Santos', country: 'Brazil' },
  { name: 'Port of Paranaguá', country: 'Brazil' },
  { name: 'Port of Buenos Aires', country: 'Argentina' },
  { name: 'Port of Valparaíso', country: 'Chile' },
  { name: 'Port of Callao', country: 'Peru' },
  { name: 'Port of Manzanillo', country: 'Mexico' },
  { name: 'Port of Veracruz', country: 'Mexico' },
  { name: 'Port of Lázaro Cárdenas', country: 'Mexico' },
  { name: 'Port of Melbourne', country: 'Australia' },
  { name: 'Port of Sydney', country: 'Australia' },
  { name: 'Port of Brisbane', country: 'Australia' },
  { name: 'Port of Fremantle', country: 'Australia' },
  { name: 'Port of Auckland', country: 'New Zealand' },
  { name: 'Port of Wellington', country: 'New Zealand' },
  { name: 'Port of Tanjung Priok', country: 'Indonesia' },
  { name: 'Port of Surabaya', country: 'Indonesia' },
  { name: 'Port of Ho Chi Minh City', country: 'Vietnam' },
  { name: 'Port of Hai Phong', country: 'Vietnam' },
  { name: 'Port of Klang', country: 'Malaysia' },
  { name: 'Port of Penang', country: 'Malaysia' },
  { name: 'Port of Manila', country: 'Philippines' },
  { name: 'Port of Cebu', country: 'Philippines' },
  { name: 'Port of Dubai', country: 'United Arab Emirates' },
  { name: 'Port of Abu Dhabi', country: 'United Arab Emirates' },
  { name: 'Port of Khalifa', country: 'United Arab Emirates' },
  { name: 'Port of Caspian Sea Terminal', country: 'Kazakhstan' },
  { name: 'Port of Aqaba', country: 'Jordan' },
  { name: 'Port of Beira', country: 'Mozambique' },
  { name: 'Port of Tema', country: 'Ghana' },
  { name: 'Port of Lagos', country: 'Nigeria' },
  { name: 'Port of Douala', country: 'Cameroon' },
  { name: 'Port of Casablanca', country: 'Morocco' },
  { name: 'Port of Tangier', country: 'Morocco' },
]

export default PORTS
